
1. Import the numpy package under the name np 

In [1]:
import numpy as np

 2. Print the numpy version and the configuration 

In [2]:
np.__version__

'1.19.2'

In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


 3. Create a null vector of size 10 

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

 4. How to find the memory size of any array 
 # Memory size of any array = array.size * array.itemsize

In [11]:
# Example to find memory size of an array
array=np.ones((5,4),dtype='int')
print("No.of items in the array: ",array.size)
print("Size of each item in the array: ",array.itemsize)
array_memory_size = array.size*array.itemsize
print("Memory size of the array: ",array_memory_size)

No.of items in the array:  20
Size of each item in the array:  4
Memory size of the array:  80


5. How to get the documentation of the numpy add function from the command line? 

Below command is used in command prompt to get documentation of the numpy add function

## python -c "import numpy; numpy.info(numpy.add)"

6. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
vector = np.zeros(10,dtype=int)
vector[4]=1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49 

In [14]:
vector1 = np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) 

In [15]:
vector1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [26]:
arr1 = np.array([1,2,0,0,4,0])
indices = np.where(arr1>0)
indices

(array([0, 1, 4], dtype=int64),)

11. Create a 3x3 identity matrix 

In [36]:
np.identity(3,dtype=int)
# np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

12. Create a 3x3x3 array with random values 

In [39]:
np.random.uniform((3,3,3))

array([2.08601734, 1.94754608, 2.26445027])

13. Create a 10x10 array with random values and find the minimum and maximum values 

In [54]:
arr2 = np.random.random((10,10)) # 10x10 array with random values
print("Minimum Value: ",arr2.min()) 
print("Maximum Value: ",arr2.max())

Minimum Value:  0.01419269206551188
Maximum Value:  0.9931528301080427


14. Create a random vector of size 30 and find the mean value 

In [56]:
vector2 = np.random.random(30)
vector2.mean()

0.4158166165119694

15. Create a 2d array with 1 on the border and 0 inside 

In [69]:
arr3 = np.ones((5,5),dtype=int)
arr3[1:-1,1:-1]=0
arr3

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

16. How to add a border (filled with 0's) around an existing array? 

In [78]:
arr4 = np.ones((5,5),dtype=int)
np.pad(arr4,pad_width=1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

17. What is the result of the following expression? 

In [79]:
print(0 *  np.nan) 
print(np.nan == np.nan) 
print(np.inf > np.nan)
print(np.nan - np.nan) 
print(np.nan in set([np.nan])) 
print(0.3 == 3 * 0.1) 

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [87]:
np.diag(np.arange(1,5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern 

CHECRKERBOARD Pattern consists of n * n squares of alternating 0 for white and 1 for black.

In [104]:
arr5 = np.ones((8,8),dtype=int)
arr5[1::2,::2]=0
arr5[::2,1::2]=0
arr5

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [110]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

21. Create a checkerboard 8x8 matrix using the tile function 

In [114]:
arr6 = np.array([[1,0],[0,1]])
checkerboard = np.tile(arr6,(4,4))
checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

22. Normalize a 5x5 random matrix 

In [120]:
# creating a 5x5 Matrix with random values
matrix1 = np.random.random((5,5)) 
# The equation for normalization is derived by initially deducting the minimum value from the variable to be normalized. 
# The minimum value is deducted from the maximum value
# and then the previous result is divided by the latter.
Normalized_Matrix = (matrix1-matrix1.min())/(matrix1.max()-matrix1.min())
Normalized_Matrix

array([[0.18764344, 0.92893966, 0.49395245, 0.87505899, 0.87725905],
       [0.08406487, 0.50681415, 0.77782356, 0.76391361, 0.03065674],
       [0.4703152 , 0.58020175, 0.03406057, 0.91864934, 1.        ],
       [0.49633214, 0.08120957, 0.05343483, 0.44393631, 0.        ],
       [0.85237621, 0.18580986, 0.20992901, 0.44594288, 0.79328677]])

23. How to find the most frequent value in an array? 

Steps to find the most frequency value in a NumPy array:

    Create a NumPy array.
    Apply bincount() method of NumPy to get the count of occurrences of each element in the array.
    The n, apply argmax() method to get the value having a maximum number of occurrences(frequency).


In [135]:
arr7 = np.array([5,2,6,7,8,5,2,5,5,6,5,8,9,1,2,3,4,4,5,2,4,6,3,4,3,5,4,5,4,5,4]) 
print("Count of occurrences of each element in the array: ",np.bincount(arr7))
print("Most frequent value in the array:", np.bincount(arr7).argmax()) 

Count of occurrences of each element in the array:  [0 1 4 3 7 9 3 1 2 1]
Most frequent value in the array: 5


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [138]:
# numpy.full() method is used to fill an array with all identical values with required shape
# numpy. full(shape, fill_value) with shape as an x, y tuple to create an array with x rows, y columns, 
# and each element as fill_value .
matrix_product = np.dot(np.full((5,3),4),np.full((3,2),6))
matrix_product

array([[72, 72],
       [72, 72],
       [72, 72],
       [72, 72],
       [72, 72]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [149]:
# creating 1D array
arr8 = np.array([2,5,2,9,7,3,4,9,5,3,8,2,2,8,2])
arr8[4:9]*=-1
arr8

array([ 2,  5,  2,  9, -7, -3, -4, -9, -5,  3,  8,  2,  2,  8,  2])

26. What is the output of the following script? 

In [150]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1)) 

10
10


27. Consider an integer vector Z, which of these expressions are legal? 

In [162]:
Z = np.arange(10)
Z**Z  # Legal Expression
2 << Z >> 2 # Legal Expression
Z <- Z # Legal Expression
1j*Z  # Legal Expression
Z/1/1 # Legal Expression
# Z<Z>Z # Illegal Expression because of ValueError: The truth value of an array with more than one element is ambiguous.

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

28. What are the result of the following expressions? 

In [163]:
print(np.array(0)  /  np.array(0))
print(np.array(0) // np.array(0)) 
print(np.array([np.nan]).astype(int).astype(float)) 

nan
0
[-2.14748365e+09]


C:\Users\NaveenKumarReddyNare\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\NaveenKumarReddyNare\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


29. How to round away from zero a float array ? 

In [164]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-5., -3.,  3.,  9., -1.,  7., -1., -7.,  3.,  9.])

30. How to find common values between two arrays? 

In [168]:
arr9 = np.arange(1,15)
arr10 = np.arange(5,20)
common_values = np.intersect1d(arr9,arr10)
common_values

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

31. How to sort an array by the nth column? 

In [178]:
# Create a 2D array
arr11 = np.array([[11, 23, 9, 22], [21, 17, 5, 14], [31, 2, 6, 7]])
# Sort array by last column
# sorted_array = array[array[row_index:column_index].argsort()]
sorted_arr = arr11[arr11[:,-1].argsort()]
sorted_arr

array([[31,  2,  6,  7],
       [21, 17,  5, 14],
       [11, 23,  9, 22]])

32. Is the following expression true? 

In [179]:
np.sqrt(-1) == np.emath.sqrt(-1) 

C:\Users\NaveenKumarReddyNare\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. How to get the dates of yesterday, today and tomorrow? 

In [187]:
print("Yesterday's Date: ",np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print("Today's Date: ",np.datetime64('today', 'D'))
print("Tomorrow's Date: ",np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

Yesterday's Date:  2020-10-31
Today's Date:  2020-11-01
Tomorrow's Date:  2020-11-02


34. How to get all the dates corresponding to the month of July 2020?

In [203]:
July_2020 = np.arange('2020-07', '2020-08', dtype='datetime64[D]')
print(July_2020)

['2020-07-01' '2020-07-02' '2020-07-03' '2020-07-04' '2020-07-05'
 '2020-07-06' '2020-07-07' '2020-07-08' '2020-07-09' '2020-07-10'
 '2020-07-11' '2020-07-12' '2020-07-13' '2020-07-14' '2020-07-15'
 '2020-07-16' '2020-07-17' '2020-07-18' '2020-07-19' '2020-07-20'
 '2020-07-21' '2020-07-22' '2020-07-23' '2020-07-24' '2020-07-25'
 '2020-07-26' '2020-07-27' '2020-07-28' '2020-07-29' '2020-07-30'
 '2020-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? 

In [202]:
A = np.ones((2,2))*1
B = np.ones((2,2))*2
C = np.ones((2,2))*3
# Caluclate (A+B) and store output in B
np.add(A,B,out=B)
# Calculate A/2 and store output in A
np.divide(A,2,out=A)
# Calculate (-A/2) - change sign of values stored in A
np.negative(A,out=A)
# Calculate B * A = ((A+B)*(-A/2)) and store final output in A
np.multiply(A,B,out=A)

array([[-1.5, -1.5],
       [-1.5, -1.5]])

36. Extract the integer part of a random array using 5 different methods 

In [207]:
arr12 = np.random.uniform(0,10,10)
# Random values in array
print(arr12)
# To extract integer part of randomly generated decimal values of a array
# Method-1 
print (arr12 - arr12%1)
# Method-2 
print (np.floor(arr12))
# Method-3 
print (np.ceil(arr12)-1)
# Method-4 
print (arr12.astype(int))
# Method-5 
print (np.trunc(arr12))

[1.71821428 9.34695036 0.90371951 8.02421559 9.68572623 2.07989594
 7.15785954 0.87508502 6.8322028  2.56044865]
[1. 9. 0. 8. 9. 2. 7. 0. 6. 2.]
[1. 9. 0. 8. 9. 2. 7. 0. 6. 2.]
[1. 9. 0. 8. 9. 2. 7. 0. 6. 2.]
[1 9 0 8 9 2 7 0 6 2]
[1. 9. 0. 8. 9. 2. 7. 0. 6. 2.]


37. Create a 5x5 matrix with row values ranging from 0 to 4 

In [210]:
matrix2 = np.zeros((5,5),dtype=int)
matrix2 += np.arange(5)
print(matrix2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array 

In [216]:
def generate_ints():
    for x in range(10):
        yield x
arr13 = np.fromiter(generate_ints(),dtype=float)
print(arr13)

0
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 

In [243]:
arr14 = np.linspace(0,1,11,endpoint=False)[1:]
print(arr14)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it 

In [242]:
sorted_vector = np.random.uniform(1,10,size=10)
sorted_vector.sort()
sorted_vector

array([2.83733068, 4.47601147, 4.96457789, 6.16189725, 6.29338275,
       6.74361835, 6.76316397, 7.16733805, 7.59046393, 9.68880332])

41. How to sum a small array faster than np.sum? 

In [245]:
arr15 = np.arange(10)
np.add.reduce(arr15)

45

42. Consider two random array A and B, check if they are equal 

In [248]:
arr16 = np.random.randint(1,5,4)
arr17 = np.random.randint(1,5,4)
# numpy.array_equal(a1, a2, equal_nan=False)
#   Returns True if two arrays have the same shape and elements, False otherwise.
Equal = np.array_equal(arr16,arr17)
print(Equal)
# numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
#   Returns True if two arrays are element-wise equal within a tolerance.
Equal = np.allclose(arr16,arr17)
print(Equal)

False
False


43. Make an array immutable (read-only) 

In [251]:
arr18 = np.ones(10,dtype=int)
arr18.flags.writeable = False
arr18[3] = 1

ValueError: assignment destination is read-only

44. .Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [254]:
arr19 = np.random.random((10,2))
print(arr19)
X,Y = arr19[:,0], arr19[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.28720066 0.95206337]
 [0.09897905 0.66571003]
 [0.9723001  0.75872826]
 [0.10657502 0.95911941]
 [0.52981174 0.65710104]
 [0.09998062 0.42805684]
 [0.185341   0.0933258 ]
 [0.15500324 0.1044097 ]
 [0.50130862 0.30425953]
 [0.99467573 0.03151882]]
[0.99443898 0.67302801 1.2333029  0.96502243 0.84408664 0.43957796
 0.20751143 0.18688871 0.5864164  0.99517498]
[1.27781612 1.4231957  0.66263995 1.46013273 0.89223385 1.34134132
 0.46647214 0.59278511 0.54549993 0.03167693]


45. Create random vector of size 10 and replace the maximum value by 0 

In [270]:
array = np.random.random((10))
array[array.argmax()] = 0
print(array)

[0.08686261 0.         0.20708498 0.75761855 0.24293455 0.60936264
 0.41323552 0.13634939 0.79793658 0.22997741]


46. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 

In [271]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


47. How to read the following file? 
 
1, 2, 3, 4, 5 
6, , , 7, 8
, , 9,10,11 
 

In [272]:
from io import StringIO# Fake file
str = StringIO('''1, 2, 3, 4, 5      
                6,  ,  , 7, 8      
                ,  , 9,10,11''')
Z = np.genfromtxt(str, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


48. Subtract the mean of each row of a matrix 

In [285]:
A = np.matrix(np.arange(1,10),dtype=int).reshape(3,3)
B = A - A.mean(axis=1)
B

matrix([[-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.]])

49. How to tell if a given 2D array has null columns? 

In [286]:
arr21 = np.random.randint(0,3,(3,10))
print((~arr21.any(axis=0)).any())

False


50. How to swap two rows of an array? 

In [288]:
arr22 = np.arange(25).reshape(5,5)
print("Before Swap: \n",arr22)
arr22[[0,1]] = arr22[[1,0]]
print("After Swap: \n",arr22)

Before Swap: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After Swap: 
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
