In [7]:
!pip install numpy==1.19.2

  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\naveenkumarreddynare\\anaconda3\\lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [9]:
import numpy

In [10]:
numpy.version.version

'1.18.1'

In [11]:
# importing numpy library
import numpy as np

In [12]:
a1 = np.array([10,20,30,40]) # pass list of elements or tuple of elements
print(a1)
print(type(a1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
# Dimensions in array
# 0-D arrays
# check array dimension with array.ndim attribute
a1 = np.array(10) # also know as scalar values
print("Array: ",a1)
print("Type of array: ", type(a1))
print("Dimension of array: ", a1.ndim)

In [ ]:
# 1-D array
# array with scalars as their elements
a1 = np.array([10,20,30,40])
print("Array: ",a1)
print("Type of array: ", type(a1))
print("Dimension of array: ", a1.ndim)

In [ ]:
# 2-D array
# array with 1-d arrays as their elements
a1 = np.array([[10,20], [30,40]])
print("Array: \n",a1)
print("Type of array: ", type(a1))
print("Dimension of array: ", a1.ndim)

In [ ]:
# 3-D array
# array with 2-d arrays as their elements
a1 = np.array([[[10,20],[30,40]], [[50, 60], [70, 80]]])
print("Array: \n",a1)
print("Type of array: ", type(a1))
print("Dimension of array: ", a1.ndim)

In [ ]:
# n-D array 
# array with n-1d arrays as their elements

In [ ]:
# creating array of higher dimension
a1 = np.array([10, 20, 30, 40, 50], ndmin = 7)
print("Array: \n",a1)
print("Type of array: ", type(a1))
print("Dimension of array: ", a1.ndim)

In [ ]:
# accessing array elements using indexing
# 1-D array
a1 = np.array([10,20,30,40]) 
print(a1)
print(a1[0])

In [ ]:
print(a1[0] + a1[1])

In [ ]:
# accessing from 2-D arrays
a1 = np.array([[10,20], [30,40]])
print(a1)
print(a1[0,0])

In [ ]:
# accessing from 3-D array
a1 = np.array([[[10,20],[30,40]], [[50, 60], [70, 80]]])
print(a1)
print(a1[0,1,1])

In [ ]:
# negative indexing
print(a1[-1,-1,0])

In [ ]:
# slicing arrays
a1 = np.array([10,20,30,40,50,60,70,80,90])
print(a1)
print(a1[0:3])

In [ ]:
# we can also mention step
print(a1[0:5])
print(a1[0:5:3])
print(a1[::2])

In [ ]:
print(a1[3:])

In [ ]:
print(a1[:3])

In [ ]:
print(a1)

In [ ]:
# negative slicing
print(a1[-4:-2])
print(a1[::-1])

In [ ]:
# slicing in higher dimensional array
a1 = np.array([[10,20,30,300], [40,50,60,400], [70,80,90,700]])
print(a1)

In [ ]:
print(a1[1, 0:2])

In [ ]:
print(a1[0:2, 0:3])

In [ ]:
print(a1[0:2, 3])

In [ ]:
# data types in python
a1 = np.array([10,20,30,40,50,60,70,80,90])
print(a1)
print(a1.dtype)

In [ ]:
a1 = np.array(["hello", "world", "I", "am", "Data", "Scientist"])
print(a1)
print(type(a1))
print(a1.dtype)

In [ ]:
ls = ["Hello", 1, "World", 5, 10]
print(ls)
a1 = np.array(["Hello", 1, "World", 5, 10])
print(a1)
print(a1.dtype)

In [ ]:
a1 = np.array([10.1, 1, 20.23, 5, 10, "hello"])
print(a1)
print(a1.dtype)

In [ ]:
a1 = np.array([10, 20, 30, 40], dtype='str')
print(a1)
print(a1.dtype)

In [ ]:
a1 = np.array(['10', '20', '30', '40'], dtype='int')
print(a1)
print(a1.dtype)

In [ ]:
# error if value can't be converted to specified data type
a1 = np.array(['Hello', '20', '30', '40'], dtype='int')
print(a1)
print(a1.dtype)

In [ ]:
print(a1)

In [ ]:
a1 = np.array(['10', '20', '30', '40'])
print(a1)
print(a1.dtype)

In [ ]:
a2 = a1.astype(int)
print(a2)
print(a2.dtype)

In [ ]:
a1 = np.array([10, 0, 30, 0])
print(a1)
print(a1.dtype)

In [ ]:
a3 = a1.astype(bool)
print(a3)

In [ ]:
# shape in numpy array
a1 = np.array([10,20,30,40])
print(a1)

In [ ]:
print(a1.shape)

In [ ]:
a1 = np.array([[10,20,30,300], [40,50,60,400], [70,80,90,700]])
print(a1)

In [ ]:
print(a1.shape)

In [ ]:
a1 = np.array([[[10,20,100,200],[30,40,100,200], [50, 60 ,600,700]], [[50, 60,100,200], [70, 80,100,200], [10,20,900,800]]])
print(a1)

In [ ]:
print(a1.shape)

In [ ]:
a1 = np.array([10,20,30,40], ndmin = 4)
print(a1)

In [ ]:
print(a1.shape)

In [ ]:
# reshape in numpy arrays
a1 = np.array([10,20,30,40,50,60])
print(a1)
print(a1.ndim)

In [ ]:
a2 = a1.reshape(2,3)
print(a2)
print(a2.ndim)

In [ ]:
print(a1)

In [ ]:
a2 = a1.reshape(1,1,3,2)
print(a2)
print(a2.ndim)

In [ ]:
print(a1)

In [ ]:
a2 = a1.reshape(2,3)
print(a2)
print(a2.shape)
print(a1.ndim)

In [ ]:
print(a1)

In [ ]:
# unknown dimennsion
a2 = a1.reshape(1,-1,2)
print(a2)
print(a2.ndim)

In [ ]:
print(a2)

In [ ]:
print(a2.ndim)
a3 = a2.reshape(-1) # converting 3d array to 1 d array this is known as flattening
print(a3)
print(a3.ndim)

In [ ]:
# iterating over numpy arrays
a1 = np.array([10,20,30,40,50,60])
print(a1)

In [ ]:
for i in a1:
    print(i)

In [ ]:
a1 = np.array([[10,20], [30,40]])
print(a1)

In [ ]:
for i in a1:
    print(i)

In [ ]:
for i in a1:
    for j in i:
        print(j)

In [ ]:
a1 = np.array([[[10,20],[30,40]], [[50, 60], [70, 80]]])
print(a1)

In [ ]:
for i in a1:
    for j in i:
        for k in j:
            print(k)

In [ ]:
# iterating using nditer()
print(a1)

In [ ]:
for i in np.nditer(a1):
    print(i)

In [ ]:
print(a1.dtype)

In [ ]:
for i in np.nditer(a1, flags=['buffered'], op_dtypes=['float']):
    print(i)

In [ ]:
print(a1)

In [ ]:
for i in np.nditer(a1, op_flags=['readwrite']):
    i[...] = i+1

In [ ]:
print(a1)

In [ ]:
for i in np.nditer(a1[:,:,::2]):
    print(i)

In [ ]:
print(a1)

In [ ]:
a1 = np.array([10,20,30,40,50,60])
print(a1)

In [ ]:
print(np.ndenumerate(a1))

In [ ]:
for index, element in np.ndenumerate(a1):
    print(index,element)

In [ ]:
a1 = np.array([[[10,20],[30,40]], [[50, 60], [70, 80]]])
print(a1)

In [ ]:
for index, element in np.ndenumerate(a1):
    print(index,element)

In [ ]:
print(a1)

In [ ]:
a1[1,1,1]

In [ ]:
#joining arrays in numpy
a1 = np.array([10,20,30,40])
a2 = np.array([50,60,70,80])

a3 = np.concatenate((a1,a2))
print(a3)

In [ ]:
a1 = np.array([[10,20], [30,40]])
a2 = np.array([[50,60], [70,80]])
print(a1)
print(a2)

In [ ]:
a3 = np.concatenate((a1,a2))
print(a3)

In [ ]:
print(a1)
print(a2)

In [ ]:
a3 = np.concatenate((a1,a2), axis = 1)
print(a3)

In [ ]:
# using stack
a1 = np.array([10,20,30,40])
a2 = np.array([50,60,70,80])

a3 = np.stack((a1,a2), axis = 1)
print(a3)

In [ ]:
# using stack
a1 = np.array([10,20,30,40])
a2 = np.array([50,60,70,80])

a3 = np.vstack((a1,a2))
print(a3)

In [ ]:
# using stack
a1 = np.array([10,20,30,40])
a2 = np.array([50,60,70,80])

a3 = np.hstack((a1,a2))
print(a3)

In [ ]:
# using stack
a1 = np.array([10,20,30,40])
a2 = np.array([50,60,70,80])

a3 = np.dstack((a1,a2))
print(a3)

In [ ]:
#splitting arrays
a1 = np.array([10,20,30,40,50,60])

a2 = np.array_split(a1,5)
print(a2)

In [ ]:
a2 = np.array_split(a1,4)
print(a2)

In [ ]:
print(a2[0])

In [ ]:
a1 = np.array([[10,20], [30,40], [50,60], [70,80], [90,100], [110,120]])
print(a1)

In [ ]:
a2 = np.array_split(a1,3)
print(a2)

In [ ]:
print(a1)

In [ ]:
a2 = np.array_split(a1, 2, axis = 1)
print(a2)

In [ ]:
print(a1)

In [ ]:
a2 = np.hsplit(a1,2)
print(a2)

In [ ]:
a2 = np.vsplit(a1,3)
print(a2)

In [ ]:
# searching element in array
a1 = np.array([10,20,30,40])
id_array = np.where(a1 == 20)
print(id_array)

In [ ]:
a1 = np.array([10,20,30,40])
id_array = np.searchsorted(a1, 30)
print(id_array)

In [ ]:
a1 = np.array([10,20,30,40])
id_array = np.searchsorted(a1, 30, side='right')
print(id_array)

In [ ]:
a1 = np.array([10,50,90])
id_array = np.searchsorted(a1,[20,70,80,100])
print(id_array)

In [ ]:
# sorting arrays
a1 = np.array([50,10,90])
sorted_array = np.sort(a1)
print(sorted_array)

In [ ]:
a1 = np.array(["apple", "banana", "mango", "apricot"])
sorted_array = np.sort(a1)
print(sorted_array)

In [ ]:
a1 = np.array(["apple", 10, "mango", 123.12])
sorted_array = np.sort(a1)
print(sorted_array)

In [ ]:
a1 = np.array([True, False, True, True])
sorted_array = np.sort(a1)
print(sorted_array)

In [ ]:
a1 = np.array([[30,10,300], [60,456, 400], [70,700, 100]])
print(a1)

In [ ]:
sorted_array = np.sort(a1)
print(sorted_array)

In [ ]:
# filtering array
a1 = np.array([10,40,20,50])
a2 = np.array([True, False, True, False])

a3 = a1[a2]
print(a3)

In [ ]:
print(a1)

In [ ]:
a2 = []

for i in a1:
    if i > 30:
        a2.append(True)
    else:
        a2.append(False)
    
a3 = a1[a2]
print(a3)

In [ ]:
a2 = a1 > 30
print(a2)

In [ ]:
a3 = a1[a2]
print(a3)

In [ ]:
# good to know functions in numpy
a1 = np.zeros(10) # creates array of zero
print(a1)

In [ ]:
a1 = np.ones(10) # creates array of one
print(a1)

In [ ]:
a1 = np.random.randint(10) # Generates random number
print(a1)

In [ ]:
a1 = np.random.randint(10, size= (3)) # Generates array of random numbers of length 3
print(a1)

In [ ]:
a1 = np.random.randint(10, size= (3,4)) # Generates array of random numbers of length 3X4
print(a1)

In [ ]:
a1 = np.array([[[10,20],[30,40]], [[50, 60], [70, 80]]])
print(a1)
print(a1.ndim)

In [ ]:
a2 = a1.flatten()
print(a2)

In [ ]:
a1 = np.random.randint(10, size= (3,4)) # Generates array of random numbers of length 3X4
print(a1)

In [ ]:
a2 = a1.T
print(a2)

In [ ]:
print(a1.max())

In [ ]:
print(a1.sum())

In [3]:
# broadcasting numpy arrays
a1 = np.array([10,30,50,60])
a2 = 10
a3 = a1 * a2
print(a3)

[100 300 500 600]


In [4]:
a1 = np.array([[10,20], [30,40]])
a2 = 10
a3 = a1 * a2
print(a3)

[[100 200]
 [300 400]]


In [5]:
a1 = np.array([[10,20], [30,40]])
a2 = np.array([2,3])
a3 = a1 * a2
print(a3)

[[ 20  60]
 [ 60 120]]
